### ISSUE TITLE
Gopls cannot work well in "Go Modules" folder

### ISSUE THREAD

**Issue by dyz1027543829** [lixvbnet/vscode-goworkspace#1]
Hi, I use `go mod` to manage package dependencies in my project, and I add "Go Modules" folder in my vscode workspace using this plugin. When I navigate from my code to go mod packages such as grpc, I find gopls reporting many errors within these go mod packages, such as:

```
could not import google.golang.org/grpc/codes (cannot find package "google.golang.org/grpc/codes" in any of 
	/usr/local/go/src/google.golang.org/grpc/codes (from $GOROOT)
	/go/src/google.golang.org/grpc/codes (from $GOPATH))compiler[BrokenImport](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#BrokenImport)
```

I suppose that these go mod packages locate in "Go Modules" folder but "Go Modules" folder itself do not contain go.mod file, so gopls switch to `$GOPATH` mode (_$GOPATH/src_) rather than `go mod` mode (_$GOPATH/pkg/mod_) for code navigation.

In order to validate my supposion above, I remove "Go Modules" folder from vscode workspace. This time when I navigate from my code to go mod packages, none error is reported by gopls and code navigation can work well within these go mod packages.

My go environment is as follows:
```
GO111MODULE="on"
GOVERSION="go1.19.5"
GOOS="linux"
GOARCH="amd64"
GOROOT="/usr/local/go"
GOPATH="/go"
GOMODCACHE="/go/pkg/mod"
GOMOD="/usr/local/go/src/go.mod"
```

So, can **vscode-goworkspace** plugin solve this problem?

**Comment by lixvbnet** [comment]
> So, can vscode-goworkspace plugin solve this problem?

Unfortunately, no.

The Go mod packages are versioned and have version suffixes in folder names. I guess gopls just can't handle that.

```
~/go/pkg/mod/google.golang.org
├── api@v0.13.0
├── appengine@v1.6.1
├── genproto@v0.0.0-20191108220845-16a3f7862a1a
├── genproto@v0.0.0-20210602131652-f16073e35f0c
├── grpc@v1.21.1
├── grpc@v1.38.0
└── protobuf@v1.26.0
```

To verify this, you can try manually remove the version suffix, and the import error would disappear.
